palette = "catppuccin_frappe"

format = """
[](blue)\
$os\
$username\
[](bg:surface0 fg:blue)\
$directory\
[](fg:surface0)\
$cmd_duration\
$fill\
$git_branch\
$c\
$nodejs\
$rust\
$python\
\n$character
"""

# Old symbol = 
add_newline = true

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "base bg:blue"
style_root = "bg:blue"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "base bg:blue"
disabled = false
format = '[$symbol]($style)'

[os.symbols]
Macos = " "
Windows = " "

[directory]
style = "bg:surface0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[fill]
symbol = ' '

[c]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[cmd_duration]
format = '[ ~$duration](italic subtext0)'
min_time = 0

[git_branch]
symbol = ""
format = '[$symbol [$branch](italic $style)]($style) '
style = "mauve dimmed"

[nodejs]
symbol = ""
format = '[$symbol [$version](italic $style)]($style)'
style = "green dimmed"

[rust]
symbol = ""
format = '[$symbol [$version](italic $style)]($style)'
style = "red dimmed"

[python]
symbol = " "
python_binary = "python3"
# You just need to put a \ before the characters to escape, its not wrapping anything it only precedes the escaped character
format = '[$symbol[($version)(\($virtualenv\))](italic $style)]($style)'
style = "green dimmed"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"
